### ISSUE TITLE
作者你好，请教一下上传图片的问题

### ISSUE THREAD

**Issue by WishMelz** [sy-records/KodoForTypecho#1]
我的wordpress转typecho的、 我之前的七牛cdn是 上传图片直接上传到服务器上，cdn那边设置的回源，相当于把url改成七牛哪个cdn的域名。我的服务器和cdn都会存在这个图片文件。 然后用了作者你这个插件这个图片只会存在cdn中，我的本地服务器中是没有这个图片的，所以请教一下怎么弄，我是前端不太懂php这种

**Comment by sy-records** [comment]
忘了，应该是都会有才对

**Comment by sy-records** [comment]
我抽空试试

**Comment by WishMelz** [comment]
好的。麻烦了
